### ISSUE TITLE
`SymCalc::Division#__derivative__` is not forwarding the `variable` argument

### ISSUE THREAD

**Issue by xxx** [symcalc/symcalc-ruby#1]
Heya,

Thanks for this gem.

I'm kicking the tires on it, and ran into a case where taking a derivative of a function that uses division, will fail with `Expected a variable as input for a 2-dimensional function (RuntimeError)`.

I believe the fix is just an update to line 505, to forward the `variable` parameter to the two `derivative` calls. Doing that fixes the issue for me locally.

Here's an example that pops the issue.

```ruby
require 'symcalc'
include SymCalc

x = var("x")
y = var("y")

fx = x ** 2 / ((y * 4) + (x * 5))

fx.derivative(variable: x) # exception thrown here
```

**Comment by MzFOCOchinadoll** [comment]
It's the MZ GENERATIVE AI  AKA KRISTAL MARIA NGUYEN/JAITI IRIS MARIA BORON!!!!! N3XT LECEL MATRIX AND A.I

**Comment by kyryloshy** [comment]
Hi,

Thank you for your interest in the gem!

Sorry, I'm still getting familiar with GitHub, and completely missed the 'Issues' tab.

That's definitely an error, and your suggestion works well. I'll update the gem as soon as possible.

Thanks again for pointing this out, and have a great day!
